/*  let meuArray =['asta','josiane',"Pedro",23,49,12.60];
console.table(meuArray);

meuArray.push("senai","ultimo");
console.table(meuArray);

meuArray.unshift('primeiro');
console.table(meuArray);


let frutas = ["Banana","Laranja","Maça","Manga","Melão","Morango","Uva","Limão"];
console.table(frutas);
frutas.splice(2,1); /* a partir do elemento "2" remover "1 elemento" */
/*
console.table(frutas);
*/

 /*  
let frutas = ["Banana","Laranja","Maça","Manga","Melão","Morango","Uva","Limão"];
console.table(frutas);
frutas.splice(0,1, "abacaxi","amora"); /* a partir do elemento "2" remover "1 elemento" */

/*console.table(frutas);

let posicao = frutas.indexOf("Uva"); /* Descobrindo a posição do elemento */
/*console.log("posicao da frutas: "+ posicao)  /*  */


/*  
Removendo com indicação da posição do elemento
let frutas = ["Banana","Laranja","Maça","Manga","Melão","Morango","Uva","Limão"];
console.table(frutas);

let posicao = frutas.indexOf("Uva");
console.log("posicao da frutas: "+ posicao);

frutas.splice(posicao,1);
console.table(frutas);
/*  */

let frutas = ["Banana","Laranja","Maça","Manga","Melão","Morango","Uva","Limão"];
frutas.sort(); /* Colocando todos os elementos em ordem */
console.table(frutas);
console.log("tamanho da matriz: " + frutas.length) /* Identificando o tamanho da matriz */
