/* Somando valores de uma matriz */
/* Criando a função com o nome SOMA*/

/*  *
function somaArray(val1,val2,val3){
    resp = val1+val2+val3;
    return resp;
}

let x = somaArray(65,3,236);
console.log("Resposta da soma: " + x)
/*  */
/*  *
function media(val1, val2, val3, val4) {
       return m (5.45 , 6.78 , 7.65 , 5.47)/4;
}
let x = media
console.log("a media" : + (5.45 , 6.78 , 7.65 , 5.47)/4)
return resultado.tofixed(2);
/*  */

/* Calcular a soma dos números de um array[] *
/*  */
/* while(soma<x.length){
     x[soma]+=soma;
     soma++
 }
/*  */


/* /
function somarArray(x){
    let soma = 0;

     for(let a = 0; a < x.length; a++) {
        soma += x[a];
    }
    return soma;
}
/* Passando os valores para arraay´[] *
let pezinho = [12,54,36,64,35,68,47,67,57];

let resultado = somarArray(pezinho)
console.log("Resultado da soma : " + resultado);/*  */

function mediaArray(x) {
    let soma = 0;

    for (let a = 0; a < x.length; a++) {
        soma += x[a];
    }
    return soma / x.length;
}

let media = [4, 8, 15, 16, 23, 42];

let resultado = mediaArray(media)
console.log("Resultado da media : " + resultado);